### ISSUE TITLE
compiling aborts in vcomputer-system

### ISSUE THREAD

**Issue by HybridDog** [trillek-team/tec#74]
l updated cmake to 3.2.2 (from there https://launchpad.net/~george-edison55/+archive/ubuntu/cmake-3.x), a cmake version higher than 3.1 should also work, shouldn't it?

Here's the error message:
```
[ 10%] Built target VCOMPUTER_STATIC
[ 59%] Built target libprotobuf
[ 68%] Built target glfw
[ 73%] Built target Bullet
[ 75%] Building CXX object CMakeFiles/TEC_LIB.dir/src/vcomputer-system.cpp.o
tec/src/vcomputer-system.cpp: In member function 'void tec::Computer::In(const tec::proto::Component&)':
tec/src/vcomputer-system.cpp:39:37: error: 'make_unique' is not a member of 'std'
     std::unique_ptr<TR3200> trcpu = std::make_unique<TR3200>();
                                     ^
tec/src/vcomputer-system.cpp:39:60: error: expected primary-expression before '>' token
     std::unique_ptr<TR3200> trcpu = std::make_unique<TR3200>();
                                                            ^
tec/src/vcomputer-system.cpp:39:62: error: expected primary-expression before ')' token
     std::unique_ptr<TR3200> trcpu = std::make_unique<TR3200>();
                                                              ^
make[3]: *** [CMakeFiles/TEC_LIB.dir/src/vcomputer-system.cpp.o] Error 1
make[2]: *** [CMakeFiles/TEC_LIB.dir/all] Error 2
make[1]: *** [CMakeFiles/TEC.dir/rule] Error 2
make: *** [TEC] Error 2
```

**Comment by adam4813** [comment]
Which version of gcc are you using? Also there will be a merging tonight of
a bunch of changes.

**Comment by HybridDog** [comment]
>Which version of gcc are you using?

gcc (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4

**Comment by jmf** [comment]
make_unique is supported only in gcc versions 4.9 and higher, which is only available in Ubuntu 15.10 and higher. 
CMake should output an error there, @adam4813 is working on solving that right now.

**Comment by HybridDog** [comment]
it also doesn't work with clang 3.8, l guess the readme isn't up to date
