### ISSUE TITLE
README.md should be updated to reflect the new VCPKG requires macOS 10.15 for building depend libraries

### ISSUE THREAD

**Issue by mochamo** [trillek-team/tec#146]
Related to building on macOS 10.14...

Building VCPKG on macOS 10.14 using ./bootstrap-vcpkg.sh results in this error:
(Using -- The C compiler identification is AppleClang 11.0.0.11000033
-- The CXX compiler identification is AppleClang 11.0.0.11000033)

```
CMake Error at CMakeLists.txt:12 (message):
  Building the vcpkg tool requires support for the C++ Filesystem TS.

  Apple clang versions 10.01 and below do not have support for it.

  Please install gcc6 or newer from homebrew (brew install gcc6).

  If you would like to try anyway, pass --allowAppleClang to bootstrap.sh.

-- Configuring incomplete, errors occurred!
```

Trying to build using macOS 10.14 with the --allowAppleClang option, (which is trying to build tec with MacOSX10.15.sdk, resulting in -mmacosx-version-min=10.14 being used as compiler options) will result in multiple related errors like this:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/filesystem:491:24: note: 'file_status' has been explicitly marked unavailable here
class _LIBCPP_TYPE_VIS file_status {
                       ^
In file included from ../src/vcpkg/base/downloads.cpp:3:
In file included from ../include/vcpkg/base/downloads.h:3:
../include/vcpkg/base/files.h:18:64: error: 'is_regular_file' is unavailable: introduced in macOS 10.15
    inline bool is_regular_file(file_status s) { return stdfs::is_regular_file(s); }
                                                               ^
```

**Comment by milesrout** [comment]
Did you try using this? https://donatstudios.com/MojaveMissingHeaderFiles

**Comment by adam4813** [comment]
@mochamo i built it on 10.14 with vcpkg there is a link in the readme to desrceibe the issue/fix a bit more

**Comment by milesrout** [comment]
thanks for pointing this out, though: it's not clear in the readme that there's an extra step required on macOS 10.14.

**Comment by mochamo** [comment]
@adam4813 did you use clang or gcc?  My problem might be I am using clang?  I now see an old comment that clang isn't supported compiling vcpkg.  Is that true?

**Comment by adam4813** [comment]
Clang is good but you may need to update the command line tools via xcode?

**Comment by milesrout** [comment]
@mochamo did you try using the instructions in the README/that link? 

```
$ sudo installer -pkg /Library/Developer/CommandLineTools/Packages
$ xcode-select --install
```

**Comment by adam4813** [comment]
@mochamo this ticket https://github.com/microsoft/vcpkg/issues/9037 is exactly the issue, so I will wait to update the README until they have a more solid resolution.

**Comment by DougStoker** [comment]
I'm not upgrading to Catalina until all my 32 bit apps have been updated.
Freaking apple.

**Comment by adam4813** [comment]
README has been updated
