### ISSUE TITLE
Linux compilation error

### ISSUE THREAD

**Issue by ziggi** [trillek-team/tec#57]
I have some errors on linking stage:
```
../lib/libTEC_LIB.a(physics-system.cpp.o): In function `tec::PhysicsSystem::Update(double)':
physics-system.cpp:(.text+0xd31): undefined reference to `btRigidBody::setMassProps(double, btVector3 const&)'
../lib/libTEC_LIB.a(physics-system.cpp.o): In function `void __gnu_cxx::new_allocator<btCapsuleShape>::construct<btCapsuleShape, float&, float&>(btCapsuleShape*, float&, float&)':
physics-system.cpp:(.text._ZN9__gnu_cxx13new_allocatorI14btCapsuleShapeE9constructIS1_JRfS4_EEEvPT_DpOT0_[_ZN9__gnu_cxx13new_allocatorI14btCapsuleShapeE9constructIS1_JRfS4_EEEvPT_DpOT0_]+0x76): undefined reference to `btCapsuleShape::btCapsuleShape(double, double)'
../lib/libTEC_LIB.a(collisionbody.cpp.o):(.rodata._ZTV23btGImpactShapeInterface[_ZTV23btGImpactShapeInterface]+0x28): undefined reference to `btCollisionShape::getBoundingSphere(btVector3&, double&) const'
../lib/libTEC_LIB.a(collisionbody.cpp.o):(.rodata._ZTV23btGImpactShapeInterface[_ZTV23btGImpactShapeInterface]+0x38): undefined reference to `btCollisionShape::getContactBreakingThreshold(double) const'
collect2: error: ld returned 1 exit status
CMakeFiles/TEC.dir/build.make:137: recipe for target 'bin/TEC' failed
make[2]: *** [bin/TEC] Error 1
CMakeFiles/Makefile2:70: recipe for target 'CMakeFiles/TEC.dir/all' failed
make[1]: *** [CMakeFiles/TEC.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

Specs:
- Arch Linux x86_64
- cmake 3.3.2
- bullet 2.83.6
- openal 1.16.0
- glew 1.12.0

**Comment by adam4813** [comment]
Looks like it isn't linking the correct bullet version. Zardoz84 will have
to check the setup since he has linux and changed some things with the
build setup.

**Comment by Zardoz89** [comment]
I would check when I arrive to my house, but I think that I simply use the bullet from /modules/, so cmake builds and links against it.

**Comment by Zardoz89** [comment]
I just check it. I don't have installed bullet on my linux machine, so I end using the bullet library from /modules/ that points to the latest bullet version -> 2.84 . I would try to see if there is a way of enforce to use it, even if there is a bullet library installed on the computer, or try to fix to get working with bullet 2.82 (what I have on Kubuntu 15.04 ).

**Comment by Zardoz89** [comment]
Try with this branch : https://github.com/Zardoz89/tec/tree/bullet_external
Now, builds&links against the bullet lib from git repo instead using libBullet-dev installed on a GNU/Linux.

**Comment by ziggi** [comment]
> Try with this branch : https://github.com/Zardoz89/tec/tree/bullet_external
> Now, builds&links against the bullet lib from git repo instead using libBullet-dev installed on a GNU/Linux.

I got this:

```
make[3]: *** No rule to make target 'Bullet-prefix/src/Bullet-build/src/BulletSoftBody/libBulletSoftBody', needed by 'bin/TEC'.  Stop.
CMakeFiles/Makefile2:107: recipe for target 'CMakeFiles/TEC.dir/all' failed
make[2]: *** [CMakeFiles/TEC.dir/all] Error 2
CMakeFiles/Makefile2:119: recipe for target 'CMakeFiles/TEC.dir/rule' failed
make[1]: *** [CMakeFiles/TEC.dir/rule] Error 2
Makefile:197: recipe for target 'TEC' failed
make: *** [TEC] Error 2
```

**Comment by Zardoz89** [comment]
Ok, I would take another look tomorrow

**Comment by Zardoz89** [comment]
I pushed a new commit that works on Windows and Linux. Try it, but first, delete "build" directory and mkdir it again before launching cmake. CMake sometimes could do weird things when  any one does  big changes on cmakelist.txt and there is files generated by the old configuration.

**Comment by ziggi** [comment]
> I pushed a new commit that works on Windows and Linux. Try it, but first, delete "build" directory and mkdir it again before launching cmake. CMake sometimes could do weird things when any one does big changes on cmakelist.txt and there is files generated by the old configuration.

Now compile worked well. Thank you.
